version: "3"
services:
  app:
    build: .
    ports:
      - 8080:8080
    environment:
      - PORT=8080

  unhealthyapp:
    build: .
    ports:
      - 8081:8081
    environment:
      - PORT=8081
      - MAKE_UNHEALTHY=1

  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
