name: build-and-push

on:
- push

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout GitHub repository
      run: gh repo clone mbigras/app .

    - name: Build Docker image
      run: ./build.sh

    - name: Test Docker image
      run: ./test.sh

    - name: Login to Docker Hub
      run: ./login.sh
      env:
        DOCKERHUB_USERNAME: "${{ secrets.DOCKERHUB_USERNAME }}"
        DOCKERHUB_TOKEN: "${{ secrets.DOCKERHUB_TOKEN }}"

    - name: Push Docker image
      run: ./push.sh
