---
name: ci

on:
  push:
    branches: master

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get app version
        id: app_version
        run: python -c 'import app; print(f"::set-output name=version::{app.__version__}")'

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags:
            - mbigras/app:${{ app_version.outputs.version }}
            - mbigras/app:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
